### ISSUE TITLE
Fix timeouts

### ISSUE THREAD

**Issue by gmickel** [gmickel/telegram-hue-bot#1]
Fix the random timeout errors that node-telegram-bot-api seems to be throwing

**Comment by gmickel** [comment]
```
Unhandled rejection TimeoutError: operation timed out
    at afterTimeout (/home/ubuntu/telegram-hue-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/timers.js:16:15)
    at timeoutTimeout (/home/ubuntu/telegram-hue-bot/node_modules/node-telegram-bot-api/node_modules/bluebird/js/main/timers.js:59:9)
    at Timer.listOnTimeout (timers.js:92:15)
```
